### ISSUE TITLE
看不太懂任务处理流程

### ISSUE THREAD

**Issue by ijiami-01** [sophgo/sophon-stream#10]
情况：有4个URL的YoloV5的例程
问题1：那么这4个URL视频流的数据是分4条线程读取，还是1条线程去读取？代码在哪？
问题2：4个URL视频流的数据被读取了后，是多条线程去分别做推理，还是1条线程去做推理？代码在哪？

**Comment by yizhou-xu** [comment]
问题1：4个线程。代码在element/multimedia/deocde。
问题2：由yolov5的配置文件决定。代码在framework/include/element.h framework/src/element.cc element/algorithm/yolov5。
