### ISSUE TITLE
rtmp 推流崩溃

### ISSUE THREAD

**Issue by xiaoxiaodetian** [sophgo/sophon-stream#20]
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 27 and format 'flv / FLV (Flash Video)'
OpenCV: FFMPEG: fallback to use tag 0x00000007/'????'
Segmentation fault

这种Segmentation fault 问题该怎么排查呢，可以生成coredump吗

**Comment by yizhou-xu** [comment]
推流是什么格式呢，rtmp吗

**Comment by xiaoxiaodetian** [comment]
rtmp

**Comment by yizhou-xu** [comment]
根据当前信息无法复现，自测可以正常推流。
![image](https://github.com/sophgo/sophon-stream/assets/160374904/eacc8bea-1b04-4a22-b384-08622b38d2d9)

**Comment by yizhou-xu** [comment]
是否是因为未开启流服务器？请参阅 https://github.com/sophgo/sophon-stream/blob/master/element/multimedia/encode/README.md 第八节

**Comment by xiaoxiaodetian** [comment]
用zlmediakit 做的流媒体服务器,在流媒体服务器上可以看到流
这是推流 element 配置
{
  "configure": {
    "encode_type": "RTMP",
    "rtsp_port": "18554",
    "rtmp_port": "19350",
    "wss_port": "9000",
    "enc_fmt": "h264_bm",
    "pix_fmt": "I420",
    "fps": 25,
    "ip": "10.18.38.123"
  },
  "shared_object": "../../build/lib/libencode.so",
  "device_id": 0,
  "id": 0,
  "name": "encode",
  "side": "sophgo",
  "thread_number": 1
}

这是engine_group 的配置
[
    {
        "graph_id": 0,
        "device_id": 0,
        "graph_name": "yolov8",
        "elements": [
            {
                "element_id": 5000,
                "element_config": "../yolov8/config/decode.json",
                "ports": {
                    "input": [
                        {
                            "port_id": 0,
                            "is_sink": false,
                            "is_src": true
                        }
                    ]
                }
            },
            {
                "element_id": 5001,
                "element_config": "../yolov8/config/yolov8_group.json",
                "inner_elements_id": [10001, 10002, 10003]
            },
            {
                "element_id": 5002,
                "element_config": "../yolov8/config/push_stream.json",
                "ports": {
                    "output": [
                        {
                            "port_id": 0,
                            "is_sink": true,
                            "is_src": false
                        }
                    ]
                }
            }
        ],
        "connections": [
            {
                "src_element_id": 5000,
                "src_port": 0,
                "dst_element_id": 5001,
                "dst_port": 0
            },
            {
                "src_element_id": 5001,
                "src_port": 0,
                "dst_element_id": 5002,
                "dst_port": 0
            }
        ]
    }
]

**Comment by yizhou-xu** [comment]
配置文件没看出明显错误，先用README里的mediamtx试试呢？

**Comment by xiaoxiaodetian** [comment]
输入单个视频流没问题，多个视频流同时输入，rtmp 推流崩溃
{
  "channels": [
    {
      "channel_id": 2,
      "url": "../yolov8/data/videos/test_car_person_1080P.avi",
      "source_type": "VIDEO",
      "sample_interval": 1,
      "loop_num": 1,
      "fps": -1
    },
    {
      "channel_id": 3,
      "url": "../yolov8/data/videos/test_car_person_1080P.avi",
      "source_type": "VIDEO",
      "sample_interval": 1,
      "loop_num": 1,
      "fps": -1
    },
    {
      "channel_id": 20,
      "url": "../yolov8/data/videos/test_car_person_1080P.avi",
      "source_type": "VIDEO",
      "sample_interval": 1,
      "loop_num": 1,
      "fps": -1
    },
    {
      "channel_id": 30,
      "url": "../yolov8/data/videos/test_car_person_1080P.avi",
      "source_type": "VIDEO",
      "sample_interval": 1,
      "loop_num": 1,
      "fps": -1
    }
  ],
  "class_names": "../yolov8/data/coco.names",
  "download_image": false,
  "draw_func_name": "draw_yolov5_results",
  "engine_config_path": "../yolov8/config/engine_group.json"
}

**Comment by yizhou-xu** [comment]
使用mediamtx，推流两路rtmp，无法复现崩溃问题。qingwen请问encode element的配置文件中线程数设置是？

**Comment by xiaoxiaodetian** [comment]
> 使用mediamtx，推流两路rtmp，无法复现崩溃问题。请问崩溃情况下，encode element的配置文件中线程数设置是？

1

**Comment by yizhou-xu** [comment]
> > 使用mediamtx，推流两路rtmp，无法复现崩溃问题。请问崩溃情况下，encode element的配置文件中线程数设置是？
> 
> 1

https://github.com/sophgo/sophon-stream/tree/master/element/multimedia/encode#2-%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0
encode插件要求线程数和编码路数一致，请参考README配置参数
