### ISSUE TITLE
处理完成后，根据推理结果的数据想要发送kafka消息，这个怎么实现

### ISSUE THREAD

**Issue by yefeilang** [sophgo/sophon-stream#22]
处理完成后，根据推理结果的数据想要发送kafka消息，这个怎么实现

**Comment by yefeilang** [comment]
1.是在哪个位置实现，后处理吗

**Comment by Yi-sir** [comment]
1. 可以新增一个element，专门做消息队列。这样好处是逻辑基本解耦，而且是异步运行。
2. 所有数据都保存在ObjectMetadata，可以阅读后处理代码了解相关结果存放在哪个结构体里。
3. 此功能可以参考tools/http_push element，这个插件是将ObjectMetadata序列化为json后，通过http协议发送。
