### ISSUE TITLE
启多个graph的时候，每个graph都有decode服务，是不是会造成统一路流重复解码

### ISSUE THREAD

**Issue by 1518515254** [sophgo/sophon-stream#23]
您好，就是我这边想实现同一路视频流，作用在不同的算法上面，现在想到的是启多个graph的方式，但是这样是不是会造成启多个decode导致性能消耗。而且如果我加了了多路视频流，比如我的人脸识别算法只识别其中一路，这个该怎么配置，我看目前的demo里面都是多路视频一起识别的。方面您有什么好的建议吗

**Comment by Yi-sir** [comment]
1. 一路视频流多个算法的需求是否可以串行？可以的话只需要一个decode，后面串联多个算法模块；
2. 如果不能串行，可以考虑使用分发-汇聚插件，把源码流分发到不同的分支上，分支之间是并行的，可以配置不同的算法；
3. 目前可以实现某路码流跳过某些element，但没有对所有的算法都适配。目前使用的场景一般还是一个graph里所有码流跑同样的流程。
