### ISSUE TITLE
编译好之后，执行sample里面的main程序会报错

### ISSUE THREAD

**Issue by 1518515254** [sophgo/sophon-stream#24]
具体报错：./main: symbol lookup error: ./main: undefined symbol: _ZN13sophon_stream9framework12ListenThread4initERKN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS3_14adl_serializerES6_IhSaIhEEvEESI_
执行的是./main --demo_config_path=../yolov8/config/yolov8_demo.json，换成其他demo的json也会报一样的错，这个有碰到过吗

**Comment by Yi-sir** [comment]
这个报错没见过，感觉是编译环境有问题。看起爱是json库相关的报错，我们的3rdparty里有一个nlohmannjson.hpp，请确定依赖的是这个头文件
