### ISSUE TITLE
预处理、推理、后处理是异步吗？

### ISSUE THREAD

**Issue by Deeperfinder** [sophgo/sophon-stream#25]
可以自定义，但M个任务，每个阶段（解码/预处理/推理/后处理/跟踪/画图/编码）最多不会超过M个线程在工作

_Originally posted by @yizhou-xu in https://github.com/sophgo/sophon-stream/issues/5#issuecomment-1961060091_

**Comment by Yi-sir** [comment]
是异步

**Comment by Deeperfinder** [comment]
可是按照 上述说法，总共才M个线程 如何做到异步呢，在代码中好像没有看到async相关的接口

**Comment by Yi-sir** [comment]
各自M个

**Comment by Deeperfinder** [comment]
方便贴一下异步的代码在哪里吗，找了很久没找到

**Comment by Yi-sir** [comment]
单个动作是同步的，各个阶段分在多个线程上了，是框架实现的

**Comment by Deeperfinder** [comment]
好的，感谢回复
