### ISSUE TITLE
faiss如何支持1684或1688

### ISSUE THREAD

**Issue by wancaidao** [sophgo/sophon-stream#28]
若自行实现faiss，如何调用TPU

**Comment by Yi-sir** [comment]
bmcv的faiss接口暂时未适配1684/1688，现在用户自行开发无法调用TPU资源。如果一定要使用faiss的数据库功能，只能使用公版接口

**Comment by wancaidao** [comment]
> bmcv的faiss接口暂时未适配1684/1688，现在用户自行开发无法调用TPU资源。如果一定要使用faiss的数据库功能，只能使用公版接口

好的，谢谢
