### ISSUE TITLE
在BM1688(SoC)上运行报错，编译最新代码报错

### ISSUE THREAD

**Issue by 15380831711** [sophgo/sophon-stream#29]
/opt/sophon/
├── libsophon-0.4.9
├── libsophon-current -> /opt/sophon/libsophon-0.4.9
├── sophon-ffmpeg-latest -> /opt/sophon/sophon-ffmpeg_1.5.0
├── sophon-ffmpeg_1.5.0
├── sophon-opencv-latest -> /opt/sophon/sophon-opencv_1.5.0
├── sophon-opencv_1.5.0
├── sophon-sample-latest -> /opt/sophon/sophon-sample_1.5.0
├── sophon-sample_1.5.0
├── sophon-soc-libisp-dev_1.0.0
└── sophon-soc-libisp_1.0.0

./main --demo_config_path=../retinaface/config/retinaface_demo.json
`element/multimedia/decode/src/decode.cc:331] channel info decoder address: 0x7f6c000b70`
**main: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.**

编译最新代码报错：
`element/algorithm/yolox/src/yolox_pre_process.cc:124:7: error: ‘bmcv_padding_atrr_t’ was not declared in this scope; did you mean ‘bmcv_padding_attr_t’?`
`element/algorithm/yolox/src/yolox_pre_process.cc:163:26: error: cannot convert ‘bm_image’ to ‘bm_image*’`

**Comment by Yi-sir** [comment]
SDK1.7版本（近期将发布）针对某些接口做了兼容，所以使用最新的代码在1.6及之前的SDK上编译会报错。目前的解决方法为：查看git log，将adapt SDK1.7这笔提交revert掉。重新编译即可通过

**Comment by Yi-sir** [comment]
https://github.com/sophgo/sophon-stream/commit/350b6984e67cbde0a76db1e751dfa3e8e1af725f
即这笔提交

**Comment by 15380831711** [comment]
> SDK1.7版本（近期将发布）针对某些接口做了兼容，所以使用最新的代码在1.6及之前的SDK上编译会报错。目前的解决方法为：查看git log，将adapt SDK1.7这笔提交revert掉。重新编译即可通过

好的，谢谢
