### ISSUE TITLE
BM1688和CV186AH的bmodel模型是通用的吗

### ISSUE THREAD

**Issue by wancaidao** [sophgo/sophon-stream#30]
发现两个平台都用BM1688的模型可以正常跑。
另外哪里可以下载到retinaface_distributor_resnet_faiss_converger案例中支持BM1688的resnet人脸特征提取模型呢？ONNX格式的也行。
这个模型可以换成ms1mv3_arcface_r18.onnx这个吗？输入不一样（[1, 3, 112, 112]），代码上需要调整吗？

**Comment by Yi-sir** [comment]
部分模型可以通用，readme里面有描述。
人脸特征提取的onnx模型，来自 https://github.com/ronghuaiyang/arcface-pytorch  我们还没有提供bmodel，可以自己转一下。
输入不一样的话，代码不需要调整。

**Comment by wancaidao** [comment]
> 部分模型可以通用，readme里面有描述。 人脸特征提取的onnx模型，来自 https://github.com/ronghuaiyang/arcface-pytorch 我们还没有提供bmodel，可以自己转一下。 输入不一样的话，代码不需要调整。

了解，多谢
