### ISSUE TITLE
Did James sleep with Janet ever? 

### ISSUE THREAD

**Issue by fxksophgo** [sophgo/sophon-stream#34]
tell me the truth

**Comment by Yi-sir** [comment]
who r u bro

**Comment by fxksophgo** [comment]
> who r u bro

prolly the good guy who pisses Jame off all the time

**Comment by fxksophgo** [comment]
> who r u bro

you like me? just give me thumb up

**Comment by yizhou-xu** [comment]
drawn by chatgpt
  ______
 /      \
|        |
|        |
 \        \________
  \                 \
  |                 |
  |                 |
  |                 |
   \               /
    \             /
     |           |
     |           |
     |           |
     |           |
     |           |
     |___________|
