### ISSUE TITLE
配置抽帧时目标跟踪需要调整什么吗

### ISSUE THREAD

**Issue by wancaidao** [sophgo/sophon-stream#35]

**Comment by Yi-sir** [comment]
这个最好是根据经验和实际运行效果来调试。element/algorithm/bytetrack/README.md 文件描述了bytetrack各个参数的含义，可以尝试一下。

**Comment by wancaidao** [comment]
> 这个最好是根据经验和实际运行效果来调试。element/algorithm/bytetrack/README.md 文件描述了bytetrack各个参数的含义，可以尝试一下。

好的，谢谢
