### ISSUE TITLE
不同设备拍摄的同一个人脸相似度不高

### ISSUE THREAD

**Issue by wancaidao** [sophgo/sophon-stream#36]
手机和枪机拍摄的人脸对比相似度不高，同设备拍摄对比还行，开启人脸对齐效果似乎更差。
还有一个问题，faiss的output_inx第一个值是相似度最高的那个吗，如何获取余弦相似度呢，还有阈值应该设为多少呢？

**Comment by Yi-sir** [comment]
1. 从文档描述来看，output_sorted_index_global_add的长度应该sort_cnt有关。当sort_cnt给1时，返回的只包含一个tensor的索引
2. 有了内积就可以计算余弦相似度了，这个可能要自己算一下
3. 啥阈值？

**Comment by wancaidao** [comment]
> 1. 从文档描述来看，output_sorted_index_global_add的长度应该sort_cnt有关。当sort_cnt给1时，返回的只包含一个tensor的索引
> 2. 有了内积就可以计算余弦相似度了，这个可能要自己算一下
> 3. 啥阈值？

1. 只返回一个索引时，这个一定都是最相似的那个吗，余弦相似度最高
2. 了解，谢谢
3. 判定为同一个人的阈值，余弦相似度

**Comment by Yi-sir** [comment]
1. 是的。另外，近期我们会整理一个faiss接口的使用说明，整理完成后我发到这里，或者同事会整理到bmcv文档上
3. 余弦相似度应该设为多少，感觉也得从实际情况看下。考虑误报和漏检等情况，综合给出一个实际采用的阈值。
