### ISSUE TITLE
已经有了yolo_group.json 为什么还需要yolo_pre.json，yolo_infer.json以及 yolo_post.json 这三个呢？

### ISSUE THREAD

**Issue by BaofengZan** [sophgo/sophon-stream#40]
你好，这三个json的作用是什么呢？

**Comment by yizhou-xu** [comment]
这三个已经不起作用了，可以看到yolov5_demo.json里面指向的是engine_group.json，而这个文件包含的就是yolov5_group.json了。

pre/infer/post这三个是老的配置方法，可以把预处理、推理、后处理分开，有些时候调试会方便。不过因为配置太冗余，所以现在合成一个了。

**Comment by BaofengZan** [comment]
好的，感谢回复
