### ISSUE TITLE
在osd插件里面获取视频时间

### ISSUE THREAD

**Issue by lilihongjava** [sophgo/sophon-stream#44]
在osd插件里面获取rtsp视频流里面的具体视频时间 有没什么好的办法
![image](https://github.com/user-attachments/assets/b60229ba-f62c-483d-b50a-95d9245e4464)

**Comment by lilihongjava** [comment]
打算通过开始时间加上帧数去计算视频里面时间，在osd插件里面可以获取到decode  的 sample_interval 吗，因为要考虑抽帧情况

**Comment by Yi-sir** [comment]
这个目前获取不到，因为插件之间是独立的。想传递数据，只能把sample_interval赋值给ObjectMetadata，然后在osd里面通过ObjectMetadata去读取
