### ISSUE TITLE
关于 检测器 element中的threadNum疑问

### ISSUE THREAD

**Issue by BaofengZan** [sophgo/sophon-stream#47]
你好，如果我只有一个video视频，然后yolov8中threadNum是2，那么实际上运行时，只有一个yolo线程运行dowork函数吗？

**Comment by Yi-sir** [comment]
两个线程都在运行，不过有一个线程取不到数据

**Comment by BaofengZan** [comment]
那如果是两个视频，然后 yolov8 两个线程，这样的话就是各自跑一个视频吗？

**Comment by Yi-sir** [comment]
是的。假设有n个线程，那么第i路码流只会进入第i%n号线程
