### ISSUE TITLE
多线程使用模型预测时为什么可以不用加锁？

### ISSUE THREAD

**Issue by BaofengZan** [sophgo/sophon-stream#48]
https://github.com/sophgo/sophon-stream/blob/12342bdc464b5aa0143f2ffcc127a5b6c83657b9/element/algorithm/yolov8/src/yolov8.cc#L246

你好，我看源码中 yolov8 element中只有一个context，如果这个element的ThreadNum大于1，这里使用模型预测时为什么可以不用加锁？

**Comment by Yi-sir** [comment]
输入输出tensor都不是成员变量，没必要加锁

**Comment by BaofengZan** [comment]
o，感谢。我明白了 ！
