### ISSUE TITLE
 sophon-stream是一个模型一条线程对多个任务，还是新增一个任务就开启一条线程？

### ISSUE THREAD

**Issue by ijiami-01** [sophgo/sophon-stream#5]
不知道stream是第一种还是第二种。

如果第一种的话，假如有4个视频流任务要检测，但如果都是用A模型，那么就只有1条线程在运行。

如果第二种的话，假如有4个视频流任务要检测，那么就会有4条线程在运行，然后每个线程都调用A模型。

**Comment by yizhou-xu** [comment]
可以自定义，但M个任务，每个阶段（解码/预处理/推理/后处理/跟踪/画图/编码）最多不会超过M个线程在工作
