### ISSUE TITLE
decode插件读取宇视的历史流出错

### ISSUE THREAD

**Issue by lilihongjava** [sophgo/sophon-stream#52]
读取海康的历史流都没有发现问题，读取宇视的实时流也没问题，但是取宇视的历史流视频固定7~8秒就会出错，视频流是正常的。
rtsp://admin:8888@XXXXX:554/c2/b1728462601/e1728462603/replay
![image](https://github.com/user-attachments/assets/6227365a-d883-4a79-b434-b77cbd399f7f)

**Comment by Yi-sir** [comment]
用sophon-ffmpeg能解吗？命令行测试一下

**Comment by lilihongjava** [comment]
![image](https://github.com/user-attachments/assets/0e9c3ee7-27c1-4df1-9c53-400451d98068)

一样8秒后出错了More than 1000 frames duplicated，我用python代码测试这个rtsp没问题的

ffmpeg -i rtsp://admin:xxxx@xxxx:554/c2/b1728462601/e1728462703/replay -f rawvideo -y /dev/null 测试命令

**Comment by Yi-sir** [comment]
ffmpeg解码会出错，但python代码测试没问题？python代码用的是什么呢

**Comment by Yi-sir** [comment]
这里的问题可能已经超过了这个repo的范围...推荐是联系相关技术支持来看一下

**Comment by lilihongjava** [comment]
python代码用是原生的ffmpeg

**Comment by lilihongjava** [comment]
python代码：`import datetime

import cv2

rtsp_url = "rtsp://admin:xxx@117.xxx:554/c2/b1728295200/e1728295380/replay"

# 构造RTSP URL
url = rtsp_url.format(start_time=start_time, end_time=end_time)
cap = cv2.VideoCapture(url)
fps = cap.get(cv2.CAP_PROP_FPS)
print(fps)
#  MPEG-4
fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
cap_size = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
desired_fps = 5  # 设定的目标帧率
videoWriter = cv2.VideoWriter('output_video.avi', fourcc, desired_fps, cap_size)
flag = True
frame_counter = 0

while flag:
    print("视频流读")
    ret, im = cap.read()
    if not ret:
        print("已无一帧图像")
        break
    videoWriter.write(im)
    frame_counter += 1

cap.release()
videoWriter.release()`

**Comment by lilihongjava** [comment]
python代码，底层是原生的ffmpeg，是没有问题的，推荐是联系相关技术支持来看一下 -- 找谁？

import datetime

import cv2

rtsp_url = "rtsp://admin:xxx@117.xxx:554/c2/b1728295200/e1728295380/replay"

# 构造RTSP URL
url = rtsp_url.format(start_time=start_time, end_time=end_time)
cap = cv2.VideoCapture(url)
fps = cap.get(cv2.CAP_PROP_FPS)
print(fps)
#  MPEG-4
fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')
cap_size = (int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)), int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)))
desired_fps = 5  # 设定的目标帧率
videoWriter = cv2.VideoWriter('output_video.avi', fourcc, desired_fps, cap_size)
flag = True
frame_counter = 0

while flag:
    print("视频流读")
    ret, im = cap.read()
    if not ret:
        print("已无一帧图像")
        break
    videoWriter.write(im)
    frame_counter += 1

cap.release()
videoWriter.release()

**Comment by Yi-sir** [comment]
联系一下产品线同事/项目经理吧，看起来是sophon-ffmpeg的问题
