### ISSUE TITLE
se9盒子上无法正常编译最新版sopone-stream源码

### ISSUE THREAD

**Issue by xiaxiaya102** [sophgo/sophon-stream#56]
操作步骤：
1.通过git拉取最新源码
2.在源码根目录中创建build目录
3.在build目录中执行 cmake .. 命令
报错如下：
![se9_1](https://github.com/user-attachments/assets/49b15732-70f9-4623-a96d-f14143753d43)
se9盒子版本信息
![ver](https://github.com/user-attachments/assets/a0df705c-820e-4aad-952b-8e05299e5a08)

**Comment by Yi-sir** [comment]
没装-dev的库。可以从官网SDK里面装，或者直接找x86的机器交叉编译
