### ISSUE TITLE
夜间室外人脸识别相似度分值很低，有什么优化方案吗？

### ISSUE THREAD

**Issue by wancaidao** [sophgo/sophon-stream#59]
有补光，人脸可以看清，但是相似度比白天低很多；人在走路或跑步状态，相似度分值更低。

**Comment by Yi-sir** [comment]
是数据库的相似度？可能是因为resnet训练时不同光照条件下的样本不均匀，导致表征向量差异较大。这种情况可能需要选用合适的数据集重新训练模型。我们提供的模型来自github的开源仓库。

**Comment by zy-Jia** [comment]
可以试试自己编译arcface相关的模型，我用的arcface的backbone_ir50_asia，监控场景下，除了侧脸效果不太行，正脸的效果还是可以的

**Comment by wancaidao** [comment]
> 是数据库的相似度？可能是因为resnet训练时不同光照条件下的样本不均匀，导致表征向量差异较大。这种情况可能需要选用合适的数据集重新训练模型。我们提供的模型来自github的开源仓库。

是的，了解了，再请教一下，你们提供的模型是通过images/face_data_train这个数据集训练的吗，images是通过下载脚本获取的

**Comment by Yi-sir** [comment]
> > 是数据库的相似度？可能是因为resnet训练时不同光照条件下的样本不均匀，导致表征向量差异较大。这种情况可能需要选用合适的数据集重新训练模型。我们提供的模型来自github的开源仓库。
> 
> 是的，了解了，再请教一下，你们提供的模型是通过images/face_data_train这个数据集训练的吗，images是通过下载脚本获取的

我们没训练模型，是从开源仓库下载的。仓库链接：https://github.com/ronghuaiyang/arcface-pytorch

**Comment by wancaidao** [comment]
> > > 是数据库的相似度？可能是因为resnet训练时不同光照条件下的样本不均匀，导致表征向量差异较大。这种情况可能需要选用合适的数据集重新训练模型。我们提供的模型来自github的开源仓库。
> > 
> > 
> > 是的，了解了，再请教一下，你们提供的模型是通过images/face_data_train这个数据集训练的吗，images是通过下载脚本获取的
> 
> 我们没训练模型，是从开源仓库下载的。仓库链接：https://github.com/ronghuaiyang/arcface-pytorch

好的，谢谢
