### ISSUE TITLE
如何获取算法处理的视频帧

### ISSUE THREAD

**Issue by xiaxiaya102** [sophgo/sophon-stream#60]
http_push插件是只有当算法识别到物体才会推流上来吗？
有方式获取到没识别出物体的视频帧吗？

**Comment by Yi-sir** [comment]
除了filter插件之外，任何插件都不会丢帧。http_push会把收到的所有帧编码发出

**Comment by xiaxiaya102** [comment]
好的，谢谢

**Comment by xiaxiaya102** [comment]
![66094d5df6fdc4fcb831320c24a349d](https://github.com/user-attachments/assets/a9387ca9-06b3-4efb-8ea5-7a705122ab26)
日志中的send data 是表示http_push插件发送了数据吗？（如果是发送数据的话，我的接口并没有收到数据）
日志输出一段时间这个后，程序会自己终止掉，日志如下：
![image](https://github.com/user-attachments/assets/208d1ab3-569c-40e4-81b9-7dc86c649b8a)
这是为什么呢

**Comment by Yi-sir** [comment]
不是，这个log可以在仓库里搜索下，和http_push没有关系。下面这个异常看不出是什么原因，可以gdb观察下先

**Comment by xiaxiaya102** [comment]
比如说我的检测区域是这个地方
![image](https://github.com/user-attachments/assets/609553d1-f375-439e-bd58-1603cf4cd9b2)
检测算法是是否吸烟，这一块区域实际上是不可能出现吸烟的情况。那这样的话，http_push插件是不是一直都不会推流了

**Comment by Yi-sir** [comment]
> 比如说我的检测区域是这个地方 ![image](https://private-user-images.githubusercontent.com/91860662/386834623-609553d1-f375-439e-bd58-1603cf4cd9b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MzU5MTMsIm5iZiI6MTczMTgzNTYxMywicGF0aCI6Ii85MTg2MDY2Mi8zODY4MzQ2MjMtNjA5NTUzZDEtZjM3NS00MzllLWJkNTgtMTYwM2NmNGNkOWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA5MjY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNmE0N2Q3YTIwMTk2OTI4ZWVjMjBiNTZmN2RmYzM3MGE5ZDFhZWRlMjdlZjc1ZGJhMmUyNTg4YzliZmFjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rfhpYdd41u3hm-pB8TgL4Kg4dofcFe_Puxw2PoZUwco) 检测算法是是否吸烟，这一块区域实际上是不可能出现吸烟的情况。那这样的话，http_push插件是不是一直都不会推流了

前面回复过了，【除了filter插件之外，任何插件都不会丢帧。http_push会把收到的所有帧编码发出】。也就是说，检测插件不丢帧，http_push也不丢帧。
