### ISSUE TITLE
请教yolov8 segment 模型，检测结果没有通过http_push发送的问题

### ISSUE THREAD

**Issue by hitlyl** [sophgo/sophon-stream#67]
执行命令为 ./main --demo_config_path=../yolov8/config/yolov8_demo.json
通过设置 download_image 为 true, 可以看到results目录下的图片上已经绘有检测框和文字， 但通过 http_push，收到的内容却没有box之类的信息。
只收到了
{"mFps":-1.1034083562270251e+30,"mFrame":{"mChannelId":0,"mEndOfStream":false,"mFrameId":600,"mHeight":1080,"mSpData":"...","mTimestamp":1734408066604043,"mWidth":1920},"mGraphId":0,"mSubId":588516048}
这样的内容。

请问应该怎么做才能收到 segment的mbox 
更进一步的想收到 segment出来的图形的points ，应该怎么做？谢谢

**Comment by Yi-sir** [comment]
可以看下 framework/common/serialize.cc: 229 到 249行的内容 ，这里对分割数据做序列化时只处理了mBox，mScores等参数，而且没有加到ObjectMetadata里。可以参考此文件添加一下。

**Comment by hitlyl** [comment]
感谢。
在cursor的帮助下已修改完成.
1. segmented_object_metadata.h 中 加入 
  common::Polygon<int> mContour; // Contour points of segmentation mask
  
2. yolov8_post_process.cc 中，postProcessSeg 函数增加取mask_image的轮廓，并放到mContour里。

            try {
              // Find contours from mask_img and store in polygon
              cv::Mat mask_u8;
              if (bbox.mask_img.empty()) {
                continue;
              }

              if (bbox.mask_img.type() != CV_8U) {
                // 将浮点mask转换为8位无符号整型
                bbox.mask_img.convertTo(mask_u8, CV_8U, 255.0);
              } else {
                mask_u8 = bbox.mask_img;
              }

              if (mask_u8.empty()) {
                continue;
              }

              std::vector<std::vector<cv::Point>> contours;
              std::vector<cv::Vec4i> hierarchy;
              try {
                cv::findContours(mask_u8, contours, hierarchy, cv::RETR_EXTERNAL, cv::CHAIN_APPROX_SIMPLE);
              } catch (const cv::Exception& e) {
                continue;
              }

              if (!contours.empty()) {
                // Get the largest contour
                size_t maxContourIdx = 0;
                double maxArea = 0;
                for (size_t i = 0; i < contours.size(); i++) {
                  double area = cv::contourArea(contours[i]);
                  if (area > maxArea) {
                    maxArea = area;
                    maxContourIdx = i;
                  }
                }

                // Store contour points in polygon
                try {
                  segData->mContour.mPoints.clear();
                  segData->mContour.mPoints.reserve(contours[maxContourIdx].size());
                  for (const auto &point : contours[maxContourIdx]) {
                    segData->mContour.mPoints.push_back(common::Point<int>(
                        point.x + segData->mBox.mX,
                        point.y + segData->mBox.mY));
                  }
                } catch (const std::exception& e) {
                  continue;
                }
              }
            } catch (const std::exception& e) {
              continue;
            }

            if (context->roi_predefined) {
              segData->mBox.mX += context->roi.start_x;
              segData->mBox.mY += context->roi.start_y;

              // Adjust contour points for ROI
              for (auto &point : segData->mContour.mPoints) {
                point.mX += context->roi.start_x;
                point.mY += context->roi.start_y;
              }
            }

            if (context->class_thresh_valid) {
              segData->mLabelName = context->class_names[segData->mClassify];
            }

            obj->mSegmentedObjectMetadatas.push_back(segData);
          }

          ++idx;
        }

3. serialize.h 中 ，添加
  // 为Point添加序列化支持
    template <typename T>
    void to_json(nlohmann::json &j, const Point<T> &point)
    {
      try {
        j = nlohmann::json{
            {"x", point.mX},
            {"y", point.mY}};
      } catch (const std::exception& e) {
        // Handle serialization error
        j = nlohmann::json::object();
      }
    }

    template <typename T>
    void from_json(const nlohmann::json &j, Point<T> &point) 
    {
      try {
        if (j.contains("x") && j.contains("y")) {
          j.at("x").get_to(point.mX);
          j.at("y").get_to(point.mY);
        }
      } catch (const std::exception& e) {
        // Handle deserialization error
        point.mX = 0;
        point.mY = 0;
      }
    }

    // 为Polygon添加序列化支持
    template <typename T>
    void to_json(nlohmann::json &j, const Polygon<T> &polygon)
    {
      try {
        j = nlohmann::json::array();
        if (!polygon.mPoints.empty()) {
          for (const auto &point : polygon.mPoints) {
            j.push_back(point);
          }
        }
      } catch (const std::exception& e) {
        // Handle serialization error
        j = nlohmann::json::array();
      }
    }

    template <typename T>
    void from_json(const nlohmann::json &j, Polygon<T> &polygon)
    {
      try {
        if (j.is_array()) {
          polygon.mPoints.clear();
          polygon.mPoints.reserve(j.size());
          for (const auto &point_json : j) {
            if (point_json.is_object()) {
              Point<T> point;
              from_json(point_json, point);
              polygon.mPoints.push_back(point);
            }
          }
        }
      } catch (const std::exception& e) {
        // Handle deserialization error
        polygon.mPoints.clear();
      }
    }

修改   NLOHMANN_JSONIFY_ALL_THINGS(SegmentedObjectMetadata, mBox, mScores, mClassify, mContour)

添加 for (auto segObj : obj->mSegmentedObjectMetadatas)
      {
        j["mSegmentedObjectMetadatas"].push_back(*segObj);
      }
