### ISSUE TITLE
web_ui怎么编译？

### ISSUE THREAD

**Issue by ijiami-01** [sophgo/sophon-stream#8]
如题，根据README我只看到要cd build，但是build里面的文件怎么生成没看到。

**Comment by yizhou-xu** [comment]
这个暂时不建议使用。如果希望使用stream+前端，可以参考我们的liteos。具体搭配方案请联系商务立项支持

**Comment by ijiami-01** [comment]
> 这个暂时不建议使用。如果希望使用stream+前端，可以参考我们的liteos。具体搭配方案请联系商务立项支持

可是我看他们的项目master分支把代码都删光了，为啥？
