### ISSUE TITLE
如果想把这个项目封装成一个服务，那么该怎么改比较好？

### ISSUE THREAD

**Issue by ijiami-01** [sophgo/sophon-stream#9]
我的情况是，偶尔会添加一个新的检测任务，也会删掉一个检测任务，也会给某个具体的检测任务增加或删除某个算法，能提供一些思路吗？是不是每次新添加一个任务，就进入一次main函数的逻辑？

**Comment by yizhou-xu** [comment]
最简单是搞多进程，一个进程对应一个任务，增加任务就开新的进程，删除任务就把某个进程kill掉。

**Comment by ijiami-01** [comment]
那复杂一点的呢？

**Comment by ijiami-01** [comment]
> 最简单是搞多进程，一个进程对应一个任务，增加任务就开新的进程，删除任务就把某个进程kill掉。

那复杂一点的呢？

**Comment by yizhou-xu** [comment]
复杂的就是你说的那样，从main里传信号
